allows hashtag hrefs in sanitize
LLK/scratch-svg-renderer pull request #337
Opened 2022-08-23 16:24 UTC by tomlum

Allows data hrefs that start with a hashtag (#) to pass through SVG sanitizing

2022-08-24 19:02 UTC, benjiwheeler requested changes

2022-08-24 19:02 UTC, benjiwheeler commented on src/sanitize-svg.js
> +        if (currentNode && currentNode.href && currentNode.href.baseVal){
This is super tiny, but: our general code style is to have a space between the closing parenthesis and the opening curly brace
```suggestion
        if (currentNode && currentNode.href && currentNode.href.baseVal) {
```

2022-08-24 19:02 UTC, benjiwheeler commented on src/sanitize-svg.js
> +            if ((href.slice(0, 5) !== 'data:') && (href.slice(0, 1) !== '#')){
```suggestion
            if ((href.slice(0, 5) !== 'data:') && (href.slice(0, 1) !== '#')) {
```

2022-08-24 19:02 UTC, benjiwheeler commented on src/sanitize-svg.js
> +                if (currentNode.attributes.getNamedItem('xlink:href')){
```suggestion
                if (currentNode.attributes.getNamedItem('xlink:href')) {
```

2022-08-24 19:02 UTC, benjiwheeler commented on src/sanitize-svg.js
> +                if (currentNode.attributes.getNamedItem('href')){
```suggestion
                if (currentNode.attributes.getNamedItem('href')) {
```

2022-08-24 19:02 UTC, benjiwheeler commented on src/sanitize-svg.js
> +            return currentNode;
Why was this `return` moved one level in? Shouldn't we always be returning it?

2022-09-08 17:59 UTC, tomlum commented on src/sanitize-svg.js
> +            return currentNode;
good catch!

2022-09-12 16:33 UTC, benjiwheeler commented
LGTM! I added a test for this, by putting before/after file versions in the fixtures dir

2022-09-12 17:59 UTC, merged